---

- name: Create common files without content
  ansible.builtin.file:
    path: '{{ item.key }}'
    owner: '{{ item.value.owner|d(omit) }}'
    group: '{{ item.value.group|d(omit) }}'
    mode: '{{ item.value.mode|d(omit) }}'
    state: '{{ item.value.state }}'
  loop: '{{ common__files|dict2items }}'
  when: item.value.state in ['touch', 'directory', 'absent']

- name: Create common files with content
  ansible.builtin.copy:
    dest: '{{ item.key }}'
    owner: '{{ item.value.owner|d(omit) }}'
    group: '{{ item.value.group|d(omit) }}'
    mode: '{{ item.value.mode|d(omit) }}'
    content: '{{ item.value.content|d(omit) }}'
  loop: '{{ common__files|dict2items }}'
  when: item.value.state in ['file']
