---

- name: Configure libuser.conf
  ansible.builtin.template:
    src: libuser.conf.j2
    dest: '{{ common__libuser_configuration_file }}'
    owner: root
    mode: 0644
  when: common__libuser_supported|bool
