---

- name: Apply hostname to host
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
  notify: ['common-gather-facts']

- name: Test for existence of file /etc/sysconfig/network
  ansible.builtin.stat:
    path: /etc/sysconfig/network
  register: _common__hosts_sysconfig
  when: ansible_os_family == 'RedHat'

- name: Apply hostname to sysconfig/network
  ansible.builtin.lineinfile:
    dest: /etc/sysconfig/network
    regexp: '^HOSTNAME\='
    line: 'HOSTNAME={{ inventory_hostname }}'
    state: present
  when: ansible_os_family == 'RedHat'
    and _common__hosts_sysconfig.stat.exists

- meta: flush_handlers

- name: Install hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
